-- INT             -- Whole Numbers
-- DECIMAL(M,N)    -- Decimal Numbers - Exact Value
-- VARCHAR(100)    -- String of text of length 100
-- BLOB            -- Binary Large Objects,Stores large data
-- DATE            -- 'YYYY-MM-DD'
-- TIMESTAMP       -- 'YYYY-MM-DD HH:MM:SS' - used for recording